[profile.default]
src = 'src'
out = 'out'
libs = ['lib']

remappings = [
"@ds-test/=lib/forge-std/lib/ds-test/src/",
"@forge-std/=lib/forge-std/src/",
"@openzeppelin/=lib/openzeppelin-contracts/",
"@solmate/=lib/solmate/src/",
"@superfluid-finance/=lib/protocol-monorepo/packages/ethereum-contracts/contracts/",
"@aave/=lib/aave-v3-core/contracts/",
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config